# Application Configuration
# Non-sensitive settings only - sensitive data (passwords) go in environment variables

database:
  host: localhost
  port: 5432
  name: postgres
  sslmode: disable

server:
  port: 8080
